import React from 'react';
import { Volume2, VolumeX, Code2, Trophy, RotateCcw, Target, Zap } from 'lucide-react';
import { DifficultyLevel, GameStats } from '../types';
import { sound } from '../utils/sound';

interface HeaderProps {
  difficulty: DifficultyLevel;
  setDifficulty: (level: DifficultyLevel) => void;
  soundEnabled: boolean;
  setSoundEnabled: (enabled: boolean) => void;
  onOpenCodeModal: () => void;
  onResetGame: () => void;
  stats: GameStats;
  isLimitedAttempts: boolean;
  setIsLimitedAttempts: (val: boolean) => void;
  attemptsLeft?: number;
  maxAttempts?: number;
}

export const Header: React.FC<HeaderProps> = ({
  difficulty,
  setDifficulty,
  soundEnabled,
  setSoundEnabled,
  onOpenCodeModal,
  onResetGame,
  stats,
  isLimitedAttempts,
  setIsLimitedAttempts,
  attemptsLeft,
  maxAttempts,
}) => {
  const levels: { id: DifficultyLevel; label: string; range: string }[] = [
    { id: 'easy', label: 'Easy', range: '1-50' },
    { id: 'standard', label: 'Standard', range: '1-100' },
    { id: 'hard', label: 'Hard', range: '1-250' },
    { id: 'extreme', label: 'Extreme', range: '1-500' },
  ];

  return (
    <header className="w-full bg-slate-900 border-b border-slate-800 sticky top-0 z-20 text-slate-100 px-4 py-3 shadow-md">
      <div className="max-w-4xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
        
        {/* Brand & Python badge */}
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-indigo-500 via-purple-500 to-amber-400 p-0.5 shadow-lg flex items-center justify-center">
            <div className="w-full h-full bg-slate-950 rounded-[10px] flex items-center justify-center">
              <Target className="w-5 h-5 text-amber-400 animate-pulse" />
            </div>
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h1 className="font-bold text-lg text-white tracking-tight">Number Guessing Game</h1>
              <span className="text-[11px] font-mono font-semibold px-2 py-0.5 rounded-full bg-emerald-500/15 text-emerald-400 border border-emerald-500/30 flex items-center gap-1">
                <Code2 className="w-3 h-3" /> Python Web App
              </span>
            </div>
            <p className="text-xs text-slate-400">Guess the secret number generated by the system!</p>
          </div>
        </div>

        {/* Quick controls */}
        <div className="flex items-center flex-wrap gap-2">
          {/* Sound Toggle */}
          <button
            id="sound-toggle-btn"
            onClick={() => {
              const next = !soundEnabled;
              setSoundEnabled(next);
              sound.enabled = next;
              if (next) sound.playClick();
            }}
            title={soundEnabled ? "Mute sound" : "Enable sound"}
            className={`p-2 rounded-lg border text-xs font-medium flex items-center gap-1.5 transition-all ${
              soundEnabled
                ? 'bg-slate-800 border-slate-700 text-amber-400 hover:bg-slate-700'
                : 'bg-slate-900 border-slate-800 text-slate-500 hover:text-slate-300'
            }`}
          >
            {soundEnabled ? <Volume2 className="w-4 h-4" /> : <VolumeX className="w-4 h-4" />}
            <span className="hidden sm:inline">{soundEnabled ? 'Sound On' : 'Muted'}</span>
          </button>

          {/* View Code */}
          <button
            id="view-python-code-btn"
            onClick={() => {
              sound.playClick();
              onOpenCodeModal();
            }}
            className="p-2 px-3 rounded-lg bg-indigo-600/20 border border-indigo-500/40 text-indigo-300 hover:bg-indigo-600/30 text-xs font-medium flex items-center gap-1.5 transition-all"
          >
            <Code2 className="w-4 h-4 text-indigo-400" />
            <span>Python Code</span>
          </button>

          {/* Restart */}
          <button
            id="new-game-btn"
            onClick={() => {
              sound.playClick();
              onResetGame();
            }}
            className="p-2 px-3 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-medium flex items-center gap-1.5 transition-all shadow-sm"
          >
            <RotateCcw className="w-4 h-4" />
            <span>New Game</span>
          </button>
        </div>
      </div>

      {/* Bar 2: Difficulty & Mode Settings */}
      <div className="max-w-4xl mx-auto mt-3 pt-3 border-t border-slate-800/80 flex flex-wrap items-center justify-between gap-3 text-xs">
        
        {/* Difficulty buttons */}
        <div className="flex items-center gap-1 overflow-x-auto pb-1 sm:pb-0">
          <span className="text-slate-400 font-medium mr-1 flex items-center gap-1">
            <Zap className="w-3.5 h-3.5 text-amber-400" /> Mode:
          </span>
          {levels.map((lvl) => {
            const active = difficulty === lvl.id;
            return (
              <button
                key={lvl.id}
                id={`diff-btn-${lvl.id}`}
                onClick={() => {
                  sound.playClick();
                  setDifficulty(lvl.id);
                }}
                className={`px-2.5 py-1 rounded-md transition-all font-mono whitespace-nowrap ${
                  active
                    ? 'bg-amber-400 text-slate-950 font-bold shadow-sm'
                    : 'bg-slate-800/80 text-slate-300 hover:bg-slate-800 hover:text-white border border-slate-700/50'
                }`}
              >
                {lvl.label} <span className="opacity-75 font-normal text-[10px]">({lvl.range})</span>
              </button>
            );
          })}
        </div>

        {/* Challenge Mode & Stats */}
        <div className="flex items-center gap-3">
          {/* Limited Tries Toggle */}
          <label className="flex items-center gap-1.5 text-slate-300 cursor-pointer bg-slate-800/60 px-2.5 py-1 rounded-md border border-slate-700/50 hover:bg-slate-800">
            <input
              type="checkbox"
              id="limited-tries-checkbox"
              checked={isLimitedAttempts}
              onChange={(e) => {
                sound.playClick();
                setIsLimitedAttempts(e.target.checked);
              }}
              className="rounded border-slate-700 text-amber-500 focus:ring-amber-500/20 bg-slate-900"
            />
            <span className="text-slate-300 font-medium">Limited Tries</span>
            {isLimitedAttempts && maxAttempts && (
              <span className="text-amber-400 font-mono font-bold">
                ({attemptsLeft}/{maxAttempts})
              </span>
            )}
          </label>

          {/* Best Score */}
          <div className="flex items-center gap-1.5 bg-slate-800/90 text-amber-300 px-2.5 py-1 rounded-md border border-amber-500/20 font-mono">
            <Trophy className="w-3.5 h-3.5 text-amber-400" />
            <span>Best: {stats.bestScoreStandard !== null ? `${stats.bestScoreStandard} guesses` : '—'}</span>
          </div>
        </div>

      </div>
    </header>
  );
};
